metrics:
    accuracy:
        class: sklearn.metrics.accuracy_score
    precision:
        class: sklearn.metrics.precision_score
        params:
            average: binary
    recall:
        class: sklearn.metrics.recall_score
        params:
            average: binary
    f2:
        class: sklearn.metrics.fbeta_score
        params:
            beta: 2
            average: binary
    roc_auc:
        class: sklearn.metrics.roc_auc_score